const PM_KEY = 'shop_payment_methods_v4';
const PROOF_KEY = 'shop_payment_proofs_v4';
function formatBRL(v){ return (Number(v)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}); }
const DEFAULT_METHODS = [
  { id:1, label:'PIX (QR)', type:'qr', value:'', active:true, description:'Pague via PIX (QR)'},
  { id:2, label:'PIX Link', type:'link', value:'', active:false, description:'Link de pagamento'},
  { id:3, label:'Transferência', type:'text', value:'Banco 001 - Agencia 0000 - Conta 000000-0', active:false, description:'Transferência bancária'}
];
function loadMethods(){ try{ const r=localStorage.getItem(PM_KEY); if(!r){ localStorage.setItem(PM_KEY, JSON.stringify(DEFAULT_METHODS)); return JSON.parse(JSON.stringify(DEFAULT_METHODS)); } return JSON.parse(r);}catch(e){ localStorage.setItem(PM_KEY, JSON.stringify(DEFAULT_METHODS)); return JSON.parse(JSON.stringify(DEFAULT_METHODS)); } }
function saveMethods(m){ localStorage.setItem(PM_KEY, JSON.stringify(m)); }
function saveProof(orderId, fileName, fileBase64){ const raw = localStorage.getItem(PROOF_KEY); const obj = raw?JSON.parse(raw):{}; if(!obj[orderId]) obj[orderId]=[]; obj[orderId].push({fileName,fileBase64,at:new Date().toISOString()}); localStorage.setItem(PROOF_KEY, JSON.stringify(obj)); }
let methods = loadMethods();
function renderMethodsList(){ const c = document.getElementById('methods-container'); c.innerHTML=''; const active = methods.filter(m=>m.active); if(active.length===0){ c.innerHTML='<div class="small">Nenhuma forma ativa.</div>'; document.getElementById('method-details').innerHTML=''; return;} active.forEach(m=>{ const card=document.createElement('div'); card.className='method-card'; card.innerHTML=`<div><strong>${m.label}</strong><div class="small">${m.description||''}</div></div>`; const btn=document.createElement('button'); btn.className='btn primary'; btn.textContent='Escolher'; btn.addEventListener('click', ()=>showMethodDetails(m.id)); card.appendChild(btn); c.appendChild(card); }); const first=methods.find(m=>m.active); if(first) showMethodDetails(first.id); }
function showMethodDetails(id){ const m = methods.find(x=>x.id==id); const d = document.getElementById('method-details'); d.innerHTML=''; if(!m) return; const h=document.createElement('h4'); h.textContent = m.label; d.appendChild(h); if(m.type==='qr'){ if(m.value){ const img=document.createElement('img'); img.src=m.value; img.style.maxWidth='320px'; img.style.border='1px solid #ddd'; img.style.borderRadius='6px'; d.appendChild(img); } else d.appendChild(document.createElement('div')).textContent='QR não configurado.'; } else if(m.type==='link'){ if(m.value){ const p=document.createElement('p'); p.innerHTML=`Abrir link: <a href="${m.value}" target="_blank">${m.value}</a>`; d.appendChild(p); const open=document.createElement('button'); open.className='btn primary'; open.textContent='Abrir link'; open.addEventListener('click', ()=>window.open(m.value,'_blank')); d.appendChild(open); } else d.appendChild(document.createElement('div')).textContent='Link não configurado.'; } else { const pre=document.createElement('pre'); pre.style.whiteSpace='pre-wrap'; pre.textContent = m.value||'Informação não configurada.'; d.appendChild(pre); } const proofBtn=document.createElement('button'); proofBtn.className='btn'; proofBtn.textContent='Já paguei — enviar comprovante'; proofBtn.addEventListener('click', ()=>document.getElementById('proof-file').click()); d.appendChild(document.createElement('br')); d.appendChild(document.createElement('br')); d.appendChild(proofBtn); }
document.addEventListener('DOMContentLoaded', ()=>{ const params = new URLSearchParams(location.search); const orderId = params.get('order') || Date.now().toString(); const amount = params.get('amount') ? parseFloat(params.get('amount')) : 59.9; document.getElementById('order-id').textContent = orderId; document.getElementById('order-amount').textContent = formatBRL(amount); renderMethodsList(); setupHiddenAdmin(); const proofFile = document.getElementById('proof-file'); proofFile.addEventListener('change', (e)=>{ const f = e.target.files[0]; if(!f) return; const reader = new FileReader(); reader.onload = function(ev){ saveProof(orderId, f.name, ev.target.result); alert('Comprovante salvo localmente (demo).'); proofFile.value=''; }; reader.readAsDataURL(f); }); });
function setupHiddenAdmin(){ let clicks=0; const t=document.getElementById('page-title'); t.addEventListener('click', ()=>{ clicks++; if(clicks===1) setTimeout(()=>{ clicks=0; },3000); if(clicks>=5){ clicks=0; openAdmin(); } }); }
function openAdmin(){ buildAdminUI(); document.getElementById('admin-modal').style.display='flex'; }
function closeAdmin(){ document.getElementById('admin-modal').style.display='none'; }
function buildAdminUI(){ const list = document.getElementById('admin-list'); list.innerHTML=''; methods.forEach((m, idx)=>{ const block = document.createElement('div'); block.style.border='1px solid #eee'; block.style.padding='8px'; block.style.marginTop='8px'; block.innerHTML = `
  <div style="display:flex;justify-content:space-between;align-items:center"><strong>Método ${idx+1}</strong>
    <label style="font-size:13px;">Ativo: <input type="checkbox" data-idx="${idx}" data-field="active" ${m.active ? 'checked' : ''}></label>
  </div>
  <div class="field"><label>Rótulo<br><input type="text" data-idx="${idx}" data-field="label" value="${escapeHtml(m.label)}" style="width:100%"></label></div>
  <div class="field"><label>Tipo<br><select data-idx="${idx}" data-field="type"><option value="qr">QR (imagem)</option><option value="link">Link (URL)</option><option value="text">Texto / Chave</option></select></label></div>
  <div class="field"><label>Valor (link/texto/base64)<br><input type="text" data-idx="${idx}" data-field="value" value="${escapeHtml(m.value||'')}" style="width:100%"></label></div>
  <div class="field"><label>Descrição<br><input type="text" data-idx="${idx}" data-field="description" value="${escapeHtml(m.description||'')}" style="width:100%"></label></div>
  <div class="field"><label>Upload imagem QR (opcional — substitui)<br><input type="file" data-idx="${idx}" data-field="upload" accept="image/*"></label></div>
  <div style="display:flex;gap:8px;margin-top:8px;"><button data-idx="${idx}" data-action="up" class="btn">↑</button><button data-idx="${idx}" data-action="down" class="btn">↓</button><button data-idx="${idx}" data-action="remove" class="btn danger">Remover</button></div>
`; list.appendChild(block); block.querySelector(`select[data-field="type"]`).value = m.type; block.querySelectorAll('[data-field]').forEach(el=>el.addEventListener('change', adminFieldChange)); block.querySelectorAll('[data-action]').forEach(btn=>btn.addEventListener('click', adminAction)); }); const addBtn = document.getElementById('admin-add'); addBtn.onclick = ()=>{ if(methods.length>=3){ alert('Máximo 3 métodos.'); return; } methods.push({ id:Date.now(), label:'Novo método', type:'text', value:'', active:true, description:'' }); buildAdminUI(); }; document.getElementById('admin-save').onclick = ()=>{ if(methods.length>3){ alert('Máximo 3 métodos.'); return; } saveMethods(methods); alert('Métodos salvos localmente.'); closeAdmin(); renderMethodsList(); }; document.getElementById('admin-close').onclick = closeAdmin; }
function adminFieldChange(e){ const el = e.target; const idx = Number(el.dataset.idx); const field = el.dataset.field; if(field==='upload'){ const f = el.files[0]; if(!f) return; const r = new FileReader(); r.onload = function(ev){ methods[idx].value = ev.target.result; methods[idx].type='qr'; buildAdminUI(); }; r.readAsDataURL(f); return; } if(field==='active'){ methods[idx].active = el.checked; return; } methods[idx][field] = el.value; }
function adminAction(e){ const action = e.target.dataset.action; const idx = Number(e.target.dataset.idx); if(action==='up' && idx>0){ const a = methods.splice(idx,1)[0]; methods.splice(idx-1,0,a); buildAdminUI(); } else if(action==='down' && idx<methods.length-1){ const a = methods.splice(idx,1)[0]; methods.splice(idx+1,0,a); buildAdminUI(); } else if(action==='remove'){ if(!confirm('Remover este método?')) return; methods.splice(idx,1); buildAdminUI(); } }
function escapeHtml(s){ return String(s||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;'); }
